import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ActiveLink } from "@/components/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className="mx-auto my-2 flex w-full justify-center sm:py-4">
						<li>
							<ActiveLink href="/">Home</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products">All</ActiveLink>
						</li>
					</ul>
				</nav>
				<section className="container mx-auto flex  w-full sm:py-4">
					{children}
				</section>
				<footer className="container mx-auto flex w-full sm:py-4">
					<p className="mx-auto">
						© {new Date().getFullYear()} Next.js, Inc.
					</p>
				</footer>
			</body>
		</html>
	);
}
